# Deployment configuration for fly.io (currently in dev mode only at
# navadmin-viewer.fly.dev)

app = "navadmin-viewer"

kill_signal = "SIGQUIT"

kill_timeout = 15

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 50
    soft_limit = 40

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    restart_limit = 5
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "2s"
    method = "get"
    path = "/about"
    protocol = "http"
    timeout = "2s"
